# This is a basic workflow to help you get started with Actions

# name: Create release branch
# on:
#  schedule:
#    - cron: '0 13 * * 2' 

name: Create release branch
on:
  push:
    branches:
      - task/DMS-5790 
    
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
         ref: task/DMS-5790
    
      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v2.1.1


      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
              
              
              

