# This is a basic workflow to help you get started with Actions

#  name: Create release branch
# on:
#  schedule:
#    - cron: '0 13 * * 2' 

name: Create release branch
on:
  push:
    branches:
      - master 
    
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
         ref: master
         
      - name: Commit and push on Develop branch
        run: git commit --allow-empty -m " MINOR, Bump minor version " && git push
  
      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v2.1.1

      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.0
        with:
          branch: 'release' 
          
  
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
              
              
              

