# This is a basic workflow to help you get started with Actions

name: Create release branch
on:
 schedule:
   - cron: '01 12 * * *'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
         ref: 'develop'
      - name: create minor version bump commit
        run: |
            git config --global user.name "bot"
            git commit --allow-empty -m " (MINOR BUMP) Bump minor version " 
            git push
      # git checkout only clones shallow, we need unshallow clone to get tags
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Get bumped version
        uses: PaulHatch/semantic-version@v2.1.1
        id: bump_version
        with:
          branch: "develop"
          # we currently don't have any prefix
          tag_prefix: ""
          # git commit message indicating a major (breaking) change
          major_pattern: "(MAJOR BUMP)"
          # git commit message indicating a minor change
          minor_pattern: "(MINOR BUMP)"
          # output format
          format: "${major}.${minor}.${patch}"
      
      # action-create-branch branches off the action's trigger branch
      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.0.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/${{ steps.bump_version.outputs.version }}'
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
         ref: 'release/${{ steps.bump_version.outputs.version }}'
      - name: create minor version bump commit
        run: |
            git config --global user.name "bot"
            git commit --allow-empty -m " create release branch " 
            git push        
      - name: Create tag
        run: |
            git tag ${{ steps.bump_version.outputs.version }}-rc1 release/${{ steps.bump_version.outputs.version }}
            git push --tags
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump_version.outputs.version }}-rc1
          release_name: ${{ steps.bump_version.outputs.version }}-rc1
          prerelease:
            true
