# This is a basic workflow to help you get started with Actions

# name: Create release branch
# on:
#  schedule:
#    - cron: '0 13 * * 2' 

name: Create release branch
on:
  push:
    branches:
      - task/DMS-5790 
    
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
         ref: task/DMS-5790

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
              
              
              
# name: Create release branch
# on:
#  schedule:
#    - cron: '0 13 * * 2' 
name: Create release branch
on:
  push:
    branches:
      - task/DMS-5790 
jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
         ref: task/DMS-5790 # should be develop
      - name: Get next version
        uses: semantic-versioning
      - name: create release branch from develop  (using the version in the branchname)
        […]
      - name: create a tag
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ name of tag from previous step }}
          release_name: Release ${{ name of tag from previous step }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          prerelease: true
          draft: true
       - name: Bump Minor Version
         # in develop branch
         git commit --allow-empty -m "MINOR: Bump minor version" && git push 

