# This is a basic workflow to help you get started with Actions

# name: Create release branch
# on:
#  schedule:
#    - cron: '0 13 * * 2' 

name: Create release branch
on:
  push
    
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Bump minor version commit
        run: git commit --allow-empty -m " MINOR, Bump minor version " && git push
      # Fetch all tags
      - run: git fetch --prune --unshallow

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v2.1.1
        id: tag_version
        with:
          # The branch to count commits on
          branch: "master"
          tag_prefix: ""
          # A string which, if present in a git commit, indicates that a change represents a major (breaking) change
          major_pattern: "(MAJOR)"
          # Same as above except indicating a minor change
          minor_pattern: "(MINOR)"
          # A string to determine the format of the version output
          format: "${major}.${minor}.${patch}"

      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.0
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/${{ steps.tag_version.outputs.version }}'
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.tag_version.outputs.version }}
          release_name: Release/${{ steps.tag_version.outputs.version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
              
              
              

